/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplemixer;

import java.awt.event.ItemEvent;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import kuusisto.tinysound.TinySound;
import kuusisto.tinysound.Music;
import kuusisto.tinysound.internal.MemMusic;

/**
 *
 * @author maj
 */
public class TrackControls extends javax.swing.JPanel {

    TinySound soundSystem; // parent's handle
    Music soundItem;
    double volume;
    
    /**
     * Creates new form TrackControls
     */
    public TrackControls() {
        initComponents();
        //this.soundSystem = ((MainFrame)this.getParent()).getSoundSystem();
        // make everything inactive when music not loaded
        PlayB.setEnabled(false);
        LoopToggleB.setEnabled(false);
        VolumeSlider.setEnabled(false);
        volume = 0.0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoadB = new javax.swing.JButton();
        PlayB = new javax.swing.JButton();
        LoopToggleB = new javax.swing.JToggleButton();
        VolumeSlider = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();

        LoadB.setText("Load");
        LoadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadBActionPerformed(evt);
            }
        });

        PlayB.setText("Play");
        PlayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayBActionPerformed(evt);
            }
        });

        LoopToggleB.setText("Loop");
        LoopToggleB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LoopToggleBItemStateChanged(evt);
            }
        });

        VolumeSlider.setMajorTickSpacing(10);
        VolumeSlider.setMinorTickSpacing(1);
        VolumeSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        VolumeSlider.setPaintTicks(true);
        VolumeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                VolumeSliderStateChanged(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField1.setText("Label1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoadB, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(PlayB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoopToggleB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VolumeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoadB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(VolumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoopToggleB)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Loads a sound.
     * @param evt unused
     */
    private void LoadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadBActionPerformed
        if (soundItem != null) {
            soundItem.unload();
            PlayB.setEnabled(false);
            LoopToggleB.setEnabled(false);
            VolumeSlider.setEnabled(false);
        }
                
        JFileChooser openDialog = new JFileChooser();
        if (openDialog.showOpenDialog(PlayB) == JFileChooser.APPROVE_OPTION) {
            File file = openDialog.getSelectedFile();
            soundItem = soundSystem.loadMusic(file);
            if (soundItem == null) {
                JOptionPane.showMessageDialog(
                        this.getParent(), 
                        "Failed to load sound file.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            PlayB.setEnabled(true);
            LoopToggleB.setEnabled(true);
            VolumeSlider.setEnabled(true);
            volume = (double)VolumeSlider.getValue() / (double)VolumeSlider.getMaximum();
            soundItem.setVolume(volume);
            System.out.println("vol: " + volume);
        }
    }//GEN-LAST:event_LoadBActionPerformed

    /**
     * Plays/pauses track
     * @param evt used to differentiate Play and Pause modes
     */
    private void PlayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayBActionPerformed
        if ( ((JButton)evt.getSource()).getText().equals("Play") ) {
            soundItem.play(false);
            ((JButton)evt.getSource()).setText("Stop");
        } else {
            soundItem.stop();
            ((JButton)evt.getSource()).setText("Play");
        }
    }//GEN-LAST:event_PlayBActionPerformed

    private void LoopToggleBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LoopToggleBItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            soundItem.play(true);
            ((JToggleButton)evt.getSource()).setText("Pause");
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            soundItem.pause();
            ((JToggleButton)evt.getSource()).setText("Loop");           
        }       
    }//GEN-LAST:event_LoopToggleBItemStateChanged

    private void VolumeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_VolumeSliderStateChanged
        volume = (double)VolumeSlider.getValue() / (double)VolumeSlider.getMaximum();
        if (soundItem != null) {
            soundItem.setVolume(volume);
        }
        System.out.println("volume:" + volume);
    }//GEN-LAST:event_VolumeSliderStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadB;
    private javax.swing.JToggleButton LoopToggleB;
    private javax.swing.JButton PlayB;
    private javax.swing.JSlider VolumeSlider;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
